desc: (none)
cmd: bin/tsp 15_city.txt 15
time_unit: i
#-----------
snapshot=0
#-----------
time=0
mem_heap_B=0
mem_heap_extra_B=0
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=1
#-----------
time=107452
mem_heap_B=900
mem_heap_extra_B=20
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=2
#-----------
time=108571
mem_heap_B=1452
mem_heap_extra_B=36
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=3
#-----------
time=110446
mem_heap_B=5548
mem_heap_extra_B=44
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=4
#-----------
time=264182
mem_heap_B=5548
mem_heap_extra_B=44
mem_stacks_B=0
heap_tree=peak
n3: 5548 (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
 n1: 4096 0x4E9E1D3: _IO_file_doallocate (filedoalloc.c:127)
  n1: 4096 0x4EAC592: _IO_doallocbuf (genops.c:398)
   n1: 4096 0x4EAB69A: _IO_file_underflow@@GLIBC_2.2.5 (fileops.c:556)
    n1: 4096 0x4EAC60C: _IO_default_uflow (genops.c:413)
     n1: 4096 0x4E8D25E: _IO_vfscanf (vfscanf.c:634)
      n1: 4096 0x4E9C8E7: __isoc99_fscanf (isoc99_fscanf.c:34)
       n1: 4096 0x400B7A: read_costs (tsp.c:79)
        n0: 4096 0x40099F: main (tsp.c:23)
 n0: 900 0x400965: main (tsp.c:16)
 n1: 552 0x4E9ECDB: __fopen_internal (iofopen.c:69)
  n1: 552 0x400B12: read_costs (tsp.c:69)
   n0: 552 0x40099F: main (tsp.c:23)
#-----------
snapshot=5
#-----------
time=264182
mem_heap_B=1452
mem_heap_extra_B=36
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=6
#-----------
time=264303
mem_heap_B=900
mem_heap_extra_B=20
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=7
#-----------
time=265548
mem_heap_B=1924
mem_heap_extra_B=28
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=8
#-----------
time=266530
mem_heap_B=1940
mem_heap_extra_B=36
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=9
#-----------
time=266568
mem_heap_B=2001
mem_heap_extra_B=47
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=10
#-----------
time=266840
mem_heap_B=2017
mem_heap_extra_B=55
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=11
#-----------
time=266878
mem_heap_B=2078
mem_heap_extra_B=66
mem_stacks_B=0
heap_tree=empty
#-----------
snapshot=12
#-----------
time=7568683351
mem_heap_B=1054
mem_heap_extra_B=58
mem_stacks_B=0
heap_tree=empty
